import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

const openSansItalic = localFont({
  src: "./fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf",
  variable: "--font-openSans-italic",
  weight: "100 900",
});

const openSans = localFont({
  src: "./fonts/OpenSans-VariableFont_wdth,wght.ttf",
  variable: "--font-openSans",
  weight: "100 900",
});

const firaCode = localFont({
  src: "./fonts/FiraCode-VariableFont_wght.ttf",
  variable: "--font-firaCode",
  weight: "300 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-background ${openSans.variable} 
        ${firaCode.variable} 
        ${openSansItalic.variable} `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
